import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.first}>
        <div className={styles.third}>
          {/* <div className=""></div> */}
          <div className={styles.fourth}>
            <div className='flex'>
              <div className="w-1/2">left</div>
              <div className="flex-1">
                <img src="/assets/images/hand.png" alt="" />
              </div>
            </div>
          </div>
        </div>
        <div className={styles.second}></div>
      </div>
    </div>
  );
}
