import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.second}></div>
      <div className={styles.first}>
        <div className={styles.third}>
          {/* <div className=""></div> */}
          <div className={`font-mangueira flex flex-col ${styles.fourth}`}>
            <div className={`flex justify-center pt-10 ${styles.gist}`}>
              <div className="bg-[#F0F1EE]/20 text-center py-2 px-4">
                <img src="/assets/images/microphone.svg" alt="" />
                <h1 className="pt-2 text-4xl font-bold text-orange font-mangueira">
                  Gist
                </h1>
              </div>
            </div>
            <div className="md:grid lg:grid-cols-2">
              <div className="w-[90%] mx-auto  md:h-full lg:h-[unset] flex justify-center">
                <div className={`md:w-5/6 md:h-[70vh] flex flex-col justify-center lg:ml-auto text-center sm:text-left ${styles.share}`}>
                  <h1 className="text-2xl mb-2 sm:mb-6 md:text-[50px] text-dark font-bold font-[Mangueira]">
                    Share the Gist
                  </h1>
                  <div className={`${styles.intro}`}>
                    <h2 className="font-medium md:text-2xl leading-relaxed">
                      Gist is the next generation of social built on top of the
                      ethereum blockchain. Consumer social will never be the
                      same. Welcome to Web3.
                    </h2>
                  </div>
                  <div className=" mt-4 sm:mt-6 bg-greyInput rounded-lg flex sm:justify-between">
                    <input
                      type="email"
                      required
                      placeholder="Enter email address"
                      className="bg-transparent w-3/5 text-sm sm:flex-1 outline-none p-4 placeholder:text-dark placeholder:font-bold"
                    />
                    <button className="bg-orange flex-1 sm:flex-grow-0 whitespace-nowrap p-3 text-sm sm:px-8 text-white font-semibold rounded-md">
                      Join Waitlist
                    </button>
                  </div>
                </div>
              </div>
              <div className="md:hidden xl:block overflow-x-hidden ml-14 sm:ml-32">
                <img 
                  src="/assets/images/hand.png"
                  alt=""
                  className={`lg:w-[36rem] 2xl:w-[36rem] xl3:w-[44rem] mx-auto mt-8 ${styles.hand}`}
                />
              </div>
            </div>
          </div>
        </div>
        <img src="/assets/images/close.svg" alt="" className={`animate-spin-slow ${styles.close}`} />
        <img src="/assets/images/small-green-circle.svg" alt="" className={`animate-bounce hidden md:block ${styles.circle}`} />
        <img src="/assets/images/small-orange-elipse.svg" alt="" className={`animate-ping-slow ${styles.orangeCircle}`} />
      </div>
    </div>
  );
}
